### ISSUE TITLE
Link to demo movie is broken.

### ISSUE THREAD

**Issue by zo0o0ot** [audreylim/go-presenter#10]
The link listed in the readme file (http://virtivia.com:27080/1vs4fiwjm924q.mov) comes up with a file not found error.

If it's possible to correct the link or upload the file somewhere else, I'd appreciate that.

**Comment by dmitshur** [comment]
The domain (and port) has changed. The following updated link should work:

http://instantshare.win/1vs4fiwjm924q.mov

**Comment by audreylim** [comment]
Thanks @dmitshur (I borrowed Dmitri's host)
