### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by fd0** [audreylim/go-presenter#3]
Hi, thanks for sharing your modification to the present tool, that's awesome!

Could you please add a paragraph in the README on how to install it?

**Comment by dmitshur** [comment]
In case this is helpful, the way I've installed it was:

``` bash
cd $GOPATH/src/golang.org/x/tools
git remote add audreylim https://github.com/audreylim/go-presenter
git fetch audreylim
git checkout audreylim/master
go install golang.org/x/tools/cmd/present
git checkout master # Restore original x/tools repo contents.
```

**Comment by dmitshur** [comment]
Also, there's a proposal to add this change upstream, see https://github.com/golang/go/issues/14654.

If accepted and completed, you will be able to do simply `go get -u golang.org/x/tools/cmd/present` to install.

**Comment by audreylim** [comment]
Thanks @shurcooL 

Updated README with installation instructions
